---
name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install project
        run: uv sync --all-extras --dev

      - name: Run pytest
        run: |
          uv run pytest --maxfail=3 --disable-warnings

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: htmlcov
          if-no-files-found: ignore
          overwrite: true
